### ISSUE TITLE
Manifest missing

### ISSUE THREAD

**Issue by AemiliusLives** [SuhasDissa/NotQuiteNitro#12]
In chrome, I get a "Manifest file is missing or unreadable. Could not load manifest" message.

**Comment by SuhasDissa** [comment]
Can you please give me more information?

- What operating system are you using ?
- Where did you save the extracted files ?
- Did you delete the files after installing the extension?

**Comment by AemiliusLives** [comment]
Chrome on windows 10, I extracted to desktop and didn't delete them. I followed the instructions and got that message.

**Comment by SuhasDissa** [comment]
I couldn't figure out the problem.

Can you just click "Load unpacked extension" and then select the folder containing extension files?

Make sure to select the right folder that contains the `manifest.json` file.

**Comment by AemiliusLives** [comment]
That worked. Thanks, and pardon the inconvenience.
