### ISSUE TITLE
Suggestion: Auto-download toggle (to hide annoying image links in some servers)

### ISSUE THREAD

**Issue by Danielshmaniel** [SuhasDissa/NotQuiteNitro#14]
I'd like it if there was a toggle to automatically hide the link (in some servers the link still shows and it's annoying), by downloading the emoji as an image in some temporary folder and attaching it, as opposed to just copying a link to a clipboard. Call this toggle "auto-download" or something like that.

**Comment by SuhasDissa** [comment]
This is not technically possible. Discord blocks third party scripts from doing network requests. So, it's not possible to download images.
